#!/bin/bash
#
# This sets up rbenv properly.

RBENV_BIN="$HOME/.rbenv/bin"

if [ ! -d "${RBENV_BIN}" ]; then
  git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
  git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
fi

if [ -d "${RBENV_BIN}" ]; then
  # Add it to the path
  export PATH="${RBENV_BIN}:$PATH"

  # Enable shims
  eval "$(rbenv init -)"
fi
